### ISSUE TITLE
Tic-tac-toe: TODO

### ISSUE THREAD

**Issue by GrayJack** [GabrielTrettel/IA_plays_something#1]
- [x] Game Loop: Choose Player 2 or AI;
- [x] Game Loop: Continue Game;
- [x] Game Loop: Check if same players;
- [x] Create Score class;
- [x] Score: Store Score on log archive;
- [x] AI: Fix the algorithm;
- [x] AI: Add level difficulty;
- [x] Choose O or X ( Player.java );
- [ ] GUI: Everything;
- [ ] Software design pattern: State or Strategy?;
